### ISSUE TITLE
Add position to statistics

### ISSUE THREAD

**Issue by britiger** [britiger/bikeparkingberlin#14]
Also analyze tag `bicycle_parking:position` on page statistics

**Comment by britiger** [comment]
Do we need more tags @tordans ?

**Comment by tordans** [comment]
No, thats all IMO.

It might be interesting to look at created_at and updated_at, but thats a different story/code and also done by https://ohsome.org/apps/dashboard/. Looking at that I don't think this analysis will be really interesting/helpful ATM.
