### ISSUE TITLE
Make data exportable

### ISSUE THREAD

**Issue by britiger** [britiger/bikeparkingberlin#15]
Create geojson export for maproulette and other qa tools like osmoscope.

**Comment by britiger** [comment]
Use clustered data! #16

**Comment by tordans** [comment]
For the MapRoulette-Challenge:

This was the example challenge we quickly set up https://maproulette.org/admin/project/2530/challenge/9417

It looks like the best way to add the data to Maproulette would be to add an external URL to the challenge. This way the data will get refreshed AFAIK. 

<img width="600" alt="Bildschirmfoto 2019-10-03 um 16 04 28" src="https://user-images.githubusercontent.com/111561/66133751-80acc580-e5f7-11e9-8ff3-ac222eb04971.png">


One important part of this, is a unique ID per result, so once the data gets refreshed it does not loose the relation between the Maproulette data and the external data. 

For the Berlin Data the `elem_nr=48540029_48540036.02` looks like a good candidate (available in the north and south data).

For the clustered data maybe just create a new hash based on all the ids inside the cluster? Or the lat/lng center of the cluster?

**Comment by britiger** [comment]
Prepare this functionality, clustering (#16) is WIP and will be added later. Same function like the geojson for the map but show all missing and remove most useless and addition fields from geojson.
