### ISSUE TITLE
Berlin: Add deeplink to the source data

### ISSUE THREAD

**Issue by tordans** [britiger/bikeparkingberlin#27]
I was looking at https://bikeparking.lorenz.lu/missingmap/Berlin#9023 and was wondering what geometry there is in the original data. To make this lookup easier, it might be useful to add a deeplink to the details-bubble.

Deeplink for this place would be 
> https://fbinter.stadt-berlin.de/fb/index.jsp?loginkey=zoomStart&mapId=k_StraDa@senstadt&bbox=394018,5814331,394238,5814490

According to the error message that shows if you remove the bbox from the URL, its also possible to use other values to place the map:
> Es wurden die Parameter 'center', 'width', 'height' oder 'bbox' nicht übergeben.

However, those values are not standard lat/lng, are they? So this is not as easy as just providing the current lat/lng to the URL?

**Comment by britiger** [comment]
Duplication #25
