### ISSUE TITLE
"rot - Tag nicht definiert" scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by tordans** [britiger/bikeparkingberlin#36]
Testcase: 
1. https://bikeparking.lorenz.lu/parkingmap#52.47569407970543/13.44902404154709/16
2. "Kapazität" + "1" auswählen
3. "grün" an/abschecken => funktioniert
"gelb" auch
ABER: "rot" scheint nichts zu ändern, die roten Pins bleiben immer stehen

Prio: IMO sehr gering aka "muss man nicht fixen". Eher FYI.

**Comment by britiger** [comment]
Grüße vom #36c3
