### ISSUE TITLE
Call JOSM over http

### ISSUE THREAD

**Issue by grischard** [britiger/bikeparkingberlin#39]
Https in JOSM is unreliable and has been dropped. See https://josm.openstreetmap.de/ticket/10033

All modern browsers support calling 127.0.0.1 over http even from https pages, per spec:

w3c/webappsec-mixed-content@349501c
https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy

JOSM's default behaviour is to run without https.

Openstreetmap.org itself also always calls JOSM over http.

**Comment by britiger** [comment]
We already changed it from https to http. You made an PR https://github.com/britiger/bikeparkingberlin/pull/33 last year. What did you mean?

**Comment by britiger** [comment]
I found some more links which have https, I'll fix it. Thanks.

**Comment by grischard** [comment]
Hah, cool! Yeah, I was surprised when bikeparkingberlin showed up in my github search and I thought I'd done that before :). Thanks for fixing this.
