### ISSUE TITLE
s_Fahrradstaender.9023 existiert nicht, ist ein Leihradständer

### ISSUE THREAD

**Issue by tordans** [britiger/bikeparkingberlin#43]
Vorab: Ich hatte versucht die ID über das Repo als "existiert nicht" zu markieren, aber das geht nur über die DB direkt, richtig? (Zumindest [finde ich nichts](https://github.com/britiger/bikeparkingberlin/search?q=do_not_exists&unscoped_q=do_not_exists))

- Location https://bikeparking.lorenz.lu/missingmap/Berlin#52.4699782995274/13.441750049823897/19/9023
- s_Fahrradstaender.9023

elem_nr | 49490008_49490021.01
-- | --
28.6531769584
5
1 | was ja [laut doku-pdf](https://fbinter.stadt-berlin.de/fb_daten/beschreibung/datenformatbeschreibung/Datenformatbeschreibung_Stra%C3%9Fenbefahrung_2014.pdf) "öffentlich" bedeutet
Fl_20150415_460

An dieser Stelle ist aber nur eine Nextbike Station https://www.openstreetmap.org/node/3709297101. Kürzlich nochmal kontrolliert.

Vorschlag: In der all app "existiert nicht" markieren

**Comment by britiger** [comment]
Richtig, Aktuell nur in der Datenbank anpzupassen. 

Ich habe mal 2 Aufgaben für mich draus gemacht:
- [ ]  Eintrag in DB ergänzen
- [ ]  Externer Login über osm.org => Es sollten nur OSM-Nutzer die Markierung vornehmen, so meine Idee
- [ ]  Einbindung zum Markieren von nicht mehr existenten Einträge

**Comment by britiger** [comment]
Eintrag als nicht vorhanden hinzugefügt:
``` 
INSERT INTO extern.external_feedback (suffix, do_not_exists, feedback, geom) 
VALUES ('berlin',true, 'Issue #43', 
  (SELECT geom from extern.all_parking_berlin WHERE elem_nr='49490008_49490021.01'));
```

**Comment by britiger** [comment]
Login und allgemeines Feedback nach #45 in eigenen Issue verschoben.

**Comment by britiger** [comment]
Für weitere aufnahmen von "Nicht existent"-Fahrradständern bitte zunächst als Issue, wenn möglich auch mehere zusammen in einem issue melden.
