### ISSUE TITLE
Add Kreuzberg Data from FixMyBerlin

### ISSUE THREAD

**Issue by tordans** [britiger/bikeparkingberlin#72]
In der Schlesischen Straße, Taborstraße und Umgebung habe ich jetzt viele, neue, großflächige Radbügel-Gruppen auf der Fahrbahn gesehen. Scheinbar werden also die Meldungen von https://fixmyberlin.de/meldungen/radbuegel/friedrichshain-kreuzberg/karte abgearbeitet.

Noch ist der Status dort „in Arbeit“; irgendwann werden die sicher anzeigen, wo genau die Bügel stehen.

Die API der Daten ist unter https://fixmyberlin.de/api/v1/reports (https://fixmyberlin.de/api).

**Comment by tordans** [comment]
@hekele hast du etwas gehört, ob es bald ein Update geben wird aus Kreuzberg, dass die Vorschlags-Daten zu offiziellen Standort-Daten macht?
Und ist geplant, das API Schema bei @FixMyBerlin in diesem Zuge nochmal zu ändern oder gleich zu halten?

Falls es gleich bleibt (und ein Update noch auf sich warten lässt), könnten wir die Vorschlags-Daten schonmal einfügen und als Indikator für OSM-Prüfungen nutzen.

**Comment by tordans** [comment]
@britiger ich habe diesen Issue kürzlich angeschaut. Wenn ich das richtig sehe, gibt es bisher keine Datenquelle, die per GeoJSON importiert / abgeglichen wird. Ich hatte überlegt, wie der einfachste Weg wäre, diese Daten einzufügen. Bspw. könnte man das GeoJSON zuerst in ein CSV umwandeln und dann den normalen CSV-Import-Prozess, der schon existiert, verwenden. Aber wahrscheinlich gibt es einfachere und sinnvollere Wege? :-)

**Comment by britiger** [comment]
Es sind zwar geo-elemente in den Daten ist aber kein geojson welches ich mit ogr2ogr importieren kann. Ich habe aber einen schnellen Prozess gefunden. Ich habe jetzt alle mit dem Status 'done' und 'execution' aufgenommen weil viele die noch auf execution stehen scheinbar schon umgesetzt sind. von den 4 done fehlen noch 3 in OSM.
