### ISSUE TITLE
New data for Neukölln, Berlin 2020

### ISSUE THREAD

**Issue by tordans** [britiger/bikeparkingberlin#80]
Ich habe von der Verwaltung Neukölln neue Daten für 2020 bekommen als Excel-Liste per Mail.
Ich gehe davon aus, dass aktuell keine OpenData wie letzten Jahr bereitgestellt werden.
Wir können die Daten aber verwenden, um die Orte abzulaufen und ggf. nachzutragen.

Kontakt via radverkehr@bezirksamt-neukoelln.de

Metadaten: 
> Projekt Anlehnbügel 2020 (ausgeführt)						
> Summe: 188		
> Stand: 10/30/2020

Laut Telefonat vorab sollten dieses Jahr Liste an Bügeln abgearbeitet werden. Bisher wurden nur die Bügel auf den Gehwegen (siehe CSV) umgesetzt; die geplanten Bügel auf der Parkspur stehen noch aus.

# Daten
Ich habe die Excel Datei etwas bereinigt und die Spalte Adresse hoffentlich optimiert, so dass das geokodieren einfacher sein dürfte. Die Originaldaten sind in einer extra Spalte.

```
Anzahl,Art,Überdacht,ÖPNV,Ort,Jahr,Adresse (bereinigt),Adresse (original)
3,A,N,N,G,2020,Sonnenallee 291,Sonnenallee 291 - vor S Köllnische Heide
4,A,N,N,G,2020,Krebsgang 10-15,Krebsgang - ggü. Eingang S Köllnische Heide
6,A,N,N,G,2020,Sonnenallee 262,Sonnenallee 262
4,A,N,N,G,2020,Aronsstraße 36,Aronsstraße 36
4,A,N,N,G,2020,Aronsstraße 46-48,Aronsstraße 46-48
4,A,N,N,G,2020,Aronsstraße 58-60,Aronsstraße 58-60
1,A,N,N,G,2020,Aronsstraße 70-72,Aronsstraße 70-72
2,A,N,N,G,2020,Aronsstraße 94-96,Aronsstraße 94-96
6,A,N,N,G,2020,Aronsstraße 108-116,Aronsstraße 108-116
2,A,N,N,G,2020,Wipperstraße 18,Wipperstr. 18
7,A,N,N,G,2020,Thiemannstraße 20-23a,Thiemannstr. 20-23a
6,A,N,N,G,2020,Thiemannstraße 15-19,Thiemannstr. 15-19
3,A,N,N,G,2020,Böhmische Straße 16,Böhmische Str. 16
4,A,N,N,G,2020,Brusendorfer Straße 5,Brusendorfer Str. 5
13,A,N,N,G,2020,Andreasberger Straße 1-11,Andreasberger Str. 1-11
1,A,N,N,G,2020,Buschrosensteig 6,Buschrosensteig 6
1,A,N,N,G,2020,Hermannstraße 232,Hermannstr. 232
2,A,N,N,G,2020,Biebricher Straße 14,Biebricher Str. 14
6,A,N,N,G,2020,Isarstraße 5-8,Isarstr. 5-8
2,A,N,N,G,2020,Isarstraße 9-10,Isarstr. 9-10
4,A,N,N,G,2020,Hermannstraße 164,Hermannstr. 164
5,A,N,N,G,2020,Hermannstraße 179,Hermannstr. 179
3,A,N,N,G,2020,Kranoldstraße 11,Kranoldstr. 11
2,A,N,N,G,2020,Jonasstraße 56,Jonasstr. 56
3,A,N,N,G,2020,Selkestraße 20A,Selkestr. ggü 20A
11,A,N,N,G,2020,Jonasstraße 44 ,Jonasstr. / Altenbraker Str. 
5,A,N,N,G,2020,Emser Straße 18,Emser Str. 18
2,A,N,N,G,2020,Weichselstraße 62,Weichselstr. 62
1,A,N,N,G,2020,Weichselstraße 6,Weichselstr. 6
4,A,N,N,G,2020,Pflügerstraße 25,Pflügerstr. Ecke Pannierstr. (Nord-Ost-Ecke)
1,A,N,N,G,2020,Weichselstraße 21-22,Weichselstr. 21/22
3,A,N,N,G,2020,Reuterstraße 36-37,Reuterstr. 36-37
3,A,N,N,G,2020,Mittelweg 4,Mittelweg 4
2,A,N,N,G,2020,Mittelweg 4,Mittelweg ggü. 4
1,A,N,N,G,2020,Hermannstraße 69,Hermannstr. 69
3,A,N,N,G,2020,Hermannstraße 198,Hermannstr. 198
2,A,N,N,G,2020,Hermannstraße 196,Hermannstr. 196
1,A,N,N,G,2020,Leykestraße 1,Leykestr. 1
4,A,N,N,G,2020,Leinestraße 17/17A,Leinestr. 17/17A
12,A,N,N,G,2020,Schillerpromenade 20-22,Schillerpromenade 20-22
3,A,N,N,G,2020,Okerstraße 34,Okerstr. 34
2,A,N,N,G,2020,Kienitzerstraße 97,Kienitzerstr. 97
4,A,N,N,G,2020,Leinestraße 17/17A,Leinestr. / Schillerpromenade (Südseite)
4,A,N,N,G,2020,Sonnenallee 127-129,Sonnenallee 127-129
2,A,N,N,G,2020,Sonnenallee 174,Sonnenallee 174
4,A,N,N,G,2020,Innstraße 38-40,Innstr. 38-40
4,A,N,N,G,2020,Okerstraße 11-12,Okerstr. 11-12
2,A,N,N,G,2020,Schönstedtstraße 15,Schönstedtstr. 15
3,A,N,N,G,2020,Finowstraße 12,Finowstr. 12
2,A,N,N,G,2020,Wildenbruchplatz 5,Wildenbruchplatz 5
2,A,N,N,G,2020,Wildenbruchplatz 6,Wildenbruchplatz 6
1,A,N,N,G,2020,Finowstraße 17,Finowstr. 17
2,A,N,N,G,2020,Finowstraße 15,Finowstr. 15
```

**Comment by britiger** [comment]
Bin dabei das zu kodieren, dabei ist mir schonmal aufgefallen:

Andreasberger Straße 1-11 betrifft ja die ganze straße: https://www.openstreetmap.org/way/5095628
Buschrosensteig 6 => nicht zu finden, nehme die 4, wenn ich da richtig sehe gibts die 6 wieder mal nicht offizell.

**Comment by britiger** [comment]
Stammen die Daten so gesehen aus der gleichen Quelle wurden aber nicht veröffentlicht? Ich würde sie einfach wie hier https://github.com/britiger/bikeparkingberlin/commit/28098be18a32d6833c535c2cd12e1208333111e4 in die vorhandenen Daten integrieren, wenn das OK ist.

**Comment by tordans** [comment]
Ich denke, das ist in Ordnung. Ganz genau betrachtet, habe ich nicht über Lizenzen gesprochen. Aber ich hab sie ja genau zu diesem Zweck angefragt und erhalten. Und ￼meiner Erinnerung nach war der ursprüngliche Datensatz auch nicht eindeutig lizensiert. Und wir importieren die Daten ja auch nicht, sondern vergleichen sie nur.
